apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/my-ts-project-default: "true"
        io.kompose.service: app
    spec:
      containers:
        - env:
            - name: ELASTIC_SEARCH_URL
              value: http://elasticsearch:9200
          image: shay88/ts-app:latest 
          name: app
          ports:
            - containerPort: 4000
              hostPort: 4000
              protocol: TCP
      restartPolicy: Always
