apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: elasticsearch
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: elasticsearch
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/my-ts-project-default: "true"
        io.kompose.service: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
          ports:
            - containerPort: 9200
              hostPort: 9200
              protocol: TCP
          env:
            - name: discovery.type
              value: single-node
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - "curl --silent --fail localhost:9200/_cluster/health || exit 1"
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 10
          resources:  # Correct placement of resources
            requests:
              memory: "2Gi"
            limits:
              memory: "4Gi"
      restartPolicy: Always